## Numpy

https://numpy.org/

● Numerical Python Linear Algebra Library

● Fundamentals for Data Analysis and Machine Learning

● Underlies SciPy, Matplotlib, Pandas, SciKit-Learn

● Logical and mathematical operations with Arrays and Matrices

● Allows you to manipulate large information

## Arrays

An array is a data structure that stores a collection of elements of the same type, arranged in a contiguous sequence in memory. Each element in an array is accessed through a numerical index, which represents its position in the sequence.

Arrays are used to efficiently store and manipulate sets of data. They can be used to store elements of primitive types such as integers, characters, floating point, as well as more complex objects.

### Array features:

All elements in an array must be of the same type. For example, an array of integers can only store integer values.

The size of an array is determined at creation time and remains fixed throughout its lifetime. It is possible to access and update the individual array elements using their indices.

Array indices generally start at zero and go up to the length of the array minus one. For example, in an array of size 5, valid indices are 0, 1, 2, 3, and 4.

Elements of an array can be accessed efficiently since their position is determined by the index and the size of the array is known.

The elements of an array are stored in contiguous memory locations, which allows direct and efficient access to the elements.

Arrays can solve a variety of problems, from storing a list of values ​​to representing multidimensional arrays. Proper use of arrays can lead to more efficient algorithms and better organization of data in a program.
![Image](https://raw.githubusercontent.com/E-man85/ML-PY/main/05-images/class2_image1.png)
![Image](https://raw.githubusercontent.com/E-man85/ML-PY/main/05-images/class2_image2.png)

### Matrix

An array is a specialized form of array, specifically a two-dimensional data structure. It arranges the elements in rows and columns, creating a rectangular table. Each matrix element is identified by a pair of indices, one for the row and one for the column.

![Image](https://raw.githubusercontent.com/E-man85/ML-PY/main/05-images/class2_image3.png)

## Practice numpy

In [1]:
# Import package to workspace
import numpy as np
# create a list
listnum = [1, 2, 3, 4, 5]
print(listnum)
# create array from list
listnum = np.array(listnum)
listnum

[1, 2, 3, 4, 5]


array([1, 2, 3, 4, 5])

In [2]:
# create array from a list of lists
listtres = [[1,2,3], [5,4,1], [3,6,7]]
listtres = np.array(listtres)
listtres


array([[1, 2, 3],
       [5, 4, 1],
       [3, 6, 7]])

In [3]:
# This function creates a one-dimensional array containing a sequence of integers, 
# starting from zero and going up to the specified (exclusive) number
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#create a one-dimensional array containing a sequence of integers.
#In this case, the arange function is used to generate a sequence of numbers starting at 0 and going up to 10 (exclusive).
#Different from the previous example (np.arange(10)), an initial value (0) and an ending value (10) are specified here.
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#The arange function also allows specifying a step (step) between elements, which by default is 1.
# In this explosion the stem is 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
# A NumPy function that creates a one-dimensional array filled with zeros
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [7]:
# a NumPy function that creates a one-dimensional array filled with ones.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
# create two-dimensional array of zeros
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
# using the linspace function
#create a one-dimensional array using NumPy's np.linspace() function.
# The linspace function generates a sequence of equally spaced numbers within a specified range.
#create an array with 15 equally spaced elements, starting from the value 1 and going up to the value 3, inclusive.
#The numbers are generated in such a way that there is an equal division between the range values.
a = np.linspace(1, 3, 15)
a

array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286, 2.        , 2.14285714, 2.28571429,
       2.42857143, 2.57142857, 2.71428571, 2.85714286, 3.        ])

In [10]:
# is a NumPy function that creates a square matrix known as an identity matrix.
#The eye function creates a matrix with ones on the main diagonal and zeros everywhere else.
#In this case, np.eye(6) creates a matrix of dimensions 6x6, where all elements on the main diagonal are equal to 1
# and all other positions are padded with zeros.
#The np.eye() function also has an optional parameter called k, which indicates the position of the diagonal that will receive the ones.
#By default, k=0, which means the ones will be on the main diagonal.
# If k is a positive value, the ones will be on a diagonal above the main diagonal, and if k is a negative value,
# the ones will be on a diagonal below the main diagonal
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [11]:
#a NumPy function that generates a one-dimensional array with random values ​​following 
# a continuous uniform distribution over the interval [0, 1).
np.random.rand(4)

array([0.62350569, 0.7148921 , 0.08586289, 0.35784839])

In [12]:
# is a NumPy function that generates a two-dimensional array with random values ​​following 
# a continuous uniform distribution over the interval [0, 1).
np.random.rand(5, 4)

array([[5.58630646e-01, 3.23639325e-01, 9.53133199e-01, 1.03424703e-01],
       [6.42892626e-01, 3.50988271e-03, 1.45041247e-01, 5.68672659e-01],
       [6.78107131e-01, 6.34348839e-01, 7.35469348e-01, 9.51270719e-01],
       [9.24911539e-04, 2.75919888e-01, 5.30173124e-01, 7.19241387e-01],
       [7.56492059e-01, 6.82722765e-01, 3.68786666e-02, 4.22609956e-01]])

In [13]:
# create arrays of random numbers that obey a normal distribution
#is a NumPy function that generates a one-dimensional array with random values ​​
# following a normal (Gaussian) distribution with mean zero and standard deviation one.
np.random.randn(7)

array([-0.26073175,  0.58382621, -1.11219997, -0.08710714,  0.12966729,
        1.49134493,  2.042807  ])

In [14]:
# is a NumPy function that generates a two-dimensional matrix with random values ​​following 
# a normal (Gaussian) distribution with mean zero and standard deviation one.
np.random.randn(3,5)

array([[-1.68300434, -0.80772079,  0.37727426,  1.24464975, -0.33954802],
       [-1.03812576, -1.84257389,  0.24225585, -1.32718366, -1.69888823],
       [-0.58015477,  0.56949957,  0.30134693, -1.00252251,  1.12644038]])

In [15]:
#a three-dimensional matrix with 4 layers, 3 rows and 2 columns, 
# filled with random values ​​following the normal distribution.
np.random.randn(4, 3, 2)

array([[[-0.21046235,  0.69249358],
        [-1.07294141, -0.66970291],
        [-0.43171738,  0.09724604]],

       [[-0.43403916,  1.15946312],
        [-0.82095778,  0.67045944],
        [ 0.27834362, -2.2442046 ]],

       [[ 0.73448339, -0.72582584],
        [ 0.0900707 ,  0.98294406],
        [-0.02261035,  1.19740631]],

       [[ 0.36173639, -2.75253068],
        [ 0.27211973,  0.03355981],
        [ 0.0089839 , -1.77909546]]])

In [16]:
# convert one-dimensional array to two-dimensional
arr = np.random.rand(25)
print(arr)
# NumPy's reshape() function is used to change the shape (shape) of an array, 
# that is, modify the number of dimensions and the size of the dimensions
#In the specific case of this line of code, the arr array is being resized to a 5x5 matrix
arr = arr.reshape(5,5)
arr

[0.16087128 0.1787149  0.50706216 0.73488563 0.6294645  0.62145686
 0.54112197 0.54387645 0.45361836 0.77172075 0.28884474 0.78491206
 0.00603458 0.57790655 0.30101693 0.30047962 0.46472515 0.68208158
 0.23740169 0.90633832 0.10866265 0.20514342 0.09994115 0.18044162
 0.11294948]


array([[0.16087128, 0.1787149 , 0.50706216, 0.73488563, 0.6294645 ],
       [0.62145686, 0.54112197, 0.54387645, 0.45361836, 0.77172075],
       [0.28884474, 0.78491206, 0.00603458, 0.57790655, 0.30101693],
       [0.30047962, 0.46472515, 0.68208158, 0.23740169, 0.90633832],
       [0.10866265, 0.20514342, 0.09994115, 0.18044162, 0.11294948]])

In [17]:
# create array of integers
np.random.randint(20)

17

In [18]:
#The np.random.randint() function has three arguments: the minimum value (inclusive), 
# the maximum value (exclusive) and the size of the array you want to generate.
#In the example, 0 is the minimum value, 20 is the maximum value and 10 is the array size
np.random.randint(0, 20, 10) 

array([13,  5,  3,  2, 13, 16,  4, 19, 11,  8])

In [19]:
# convert between dimensions
a = np.arange(6).reshape((3, 2))
print(a)
# is used to change the form (shape) of an array, that is, modify the number of dimensions 
# and the size of the dimensions.
#In the specific case of this line of code, the array a is being resized to a 2x3 matrix.
a = np.reshape(a, (2, 3))
a

[[0 1]
 [2 3]
 [4 5]]


array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
# minimum and maximum elements and indices
arr2 = np.random.randint(0, 20, 10) 
print(arr2)
#maximum
print('\nMaximun\n',arr2.max()) 
#Minimum
print('\nMinimum\n',arr2.min())
#returns the index of the element with the maximum value in a NumPy one-dimensional arr2 array
print('\nMaximum Index\n',arr2.argmax())
#returns the index of the element with the minimum value in a NumPy one-dimensional arr2 array
print('\nMinimum Index\n',arr2.argmin())

[ 7 19  0  1  3  6  5 10 14  0]

Maximun
 19

Minimum
 0

Maximum Index
 1

Minimum Index
 2


In [21]:
# arr array form
print(arr.shape)
# arr2 array shape
arr2.shape

(5, 5)


(10,)

In [22]:
# indexing and selection of elements or groups of elements
arr = np.random.rand(10)
print(arr)
arr[8] # element positioned at index 8


[0.38586344 0.51818744 0.77914256 0.6669204  0.5186676  0.88000338
 0.40722588 0.48107223 0.39952936 0.54360849]


0.399529362679659

In [23]:
# returns everything between indexes 2 and 6 (exclusive)
arr[2:6]  

array([0.77914256, 0.6669204 , 0.5186676 , 0.88000338])

In [24]:
# returns everything between indexes 0 and 6 (exclusive)
arr[:6]   

array([0.38586344, 0.51818744, 0.77914256, 0.6669204 , 0.5186676 ,
       0.88000338])

In [25]:
# returns everything between index 5 and the final index
arr[5:] 

array([0.88000338, 0.40722588, 0.48107223, 0.39952936, 0.54360849])

In [26]:
# in two dimensions...
arr2d = np.array([[10,20,30], [40,50,60], [70,80,90]])
print(arr2d)
# the value 60 appears in the row with index 1 and column with index 2
print(arr2d[1][2])
# other way
arr2d[1,2] 

[[10 20 30]
 [40 50 60]
 [70 80 90]]
60


60

In [27]:
# subset or slice of the array
arr2d[:1, :2]
print(arr2d[:2, 1:])
print(arr2d[:2, :2])

[[20 30]
 [50 60]]
[[10 20]
 [40 50]]


In [28]:
# the entire line with index 0
arr2d[0]  

array([10, 20, 30])

In [29]:
# all rows with indices less than 2
arr2d[:2] 

array([[10, 20, 30],
       [40, 50, 60]])

In [30]:
# selection with logical and conditional operators
arr = np.arange(5,15)
print(arr)
# returns TRUE where elements are greater than 10
arr > 10 

[ 5  6  7  8  9 10 11 12 13 14]


array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [31]:
boolarr = arr > 10
boolarr

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [32]:
# array elements greater than 10
arr[boolarr] 

array([11, 12, 13, 14])

In [33]:
# same as above but with simpler approach
arr[arr > 10]

array([11, 12, 13, 14])

In [34]:
# combination of conditions
arr[(arr > 6) & (arr < 10)]

array([7, 8, 9])

In [35]:
# broadcasting - assignment of the value 50 to the first 3 elements of the array
arr[0:3] = 50
arr

array([50, 50, 50,  8,  9, 10, 11, 12, 13, 14])

In [36]:
# arithmetic operations
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
# multiply
arr * arr 

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [38]:
# subtract
arr - arr  

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
# he adds
arr + arr  

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [40]:
arr / arr  # divide

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
# add 50 to each array element
arr + 50 

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [42]:
# function application
# square root of each element
np.sqrt(arr)  

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [43]:
# exponential
np.exp(arr)   

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [44]:
np.sin(arr) # sin

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [45]:
np.cos(arr) # cosine

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [46]:
np.log(arr) # logarithm

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [47]:
np.sum(arr) # sum

55

In [48]:
np.std(arr) # standard deviation

2.8722813232690143

In [49]:
np.mean(arr) # mean

5.5

In [50]:
# sum of array elements (total, by row or column)
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [51]:
mat.sum() #sum of array elements

325

In [52]:
# calculate the sum of the elements of a mat matrix along the 0 axis. that is,
#  we are summing the elements of each column
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [53]:
# calculate the sum of the elements of a mat matrix along the 1 axis. i.e. we are summing the elements of each row
mat.sum(axis=1) 

array([ 15,  40,  65,  90, 115])

In [54]:
# other operations
t = np.array([1.0,5.55, 123, 0.567, 25.532]) 
t

array([  1.   ,   5.55 , 123.   ,   0.567,  25.532])

In [55]:
# evenly round to the given number of decimals
np.around(t) 

array([  1.,   6., 123.,   1.,  26.])

In [56]:
np.around(t, decimals = 1) 

array([  1. ,   5.6, 123. ,   0.6,  25.5])

In [57]:
 # return the ceiling of the input, element-wise.
np.ceil(t) 

array([  1.,   6., 123.,   1.,  26.])

In [58]:
np.fix(t)   # round to nearest integer towards zero.

array([  1.,   5., 123.,   0.,  25.])

In [59]:
np.floor(t) # return the floor of the input, element-wise.

array([  1.,   5., 123.,   0.,  25.])

In [60]:
#The np.rint() function rounds the elements of t according to the following rules:
#If the element is exactly in the middle of the range between two integers, the closest integer is returned,
# being rounded to the nearest even number in case of a tie.
# If the element is closer to the larger integer, it is rounded up.
# If the element is closer to the smallest integer, it is rounded down.
np.rint(t)  # round elements of the array to the nearest integer.

array([  1.,   6., 123.,   1.,  26.])

In [61]:
# returns the integer part of each element in an array t, discarding decimal values.
np.trunc(t) 

array([  1.,   5., 123.,   0.,  25.])

In [62]:
# numpy multiple operators
a = np.linspace(1,10,15).reshape(3, 5)
a

array([[ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857],
       [ 4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429],
       [ 7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ]])

In [63]:
a.shape # array shape

(3, 5)

In [64]:
a.ndim # array dimension

2

In [65]:
a.dtype.name # type of variable stored in the array

'float64'

In [66]:
a.size # number of array elements

15

In [67]:
type(a)  # object type (in this case it identifies as array)

numpy.ndarray

In [68]:
a.T # transposition
np.transpose(a) # another way to call the command

array([[ 1.        ,  4.21428571,  7.42857143],
       [ 1.64285714,  4.85714286,  8.07142857],
       [ 2.28571429,  5.5       ,  8.71428571],
       [ 2.92857143,  6.14285714,  9.35714286],
       [ 3.57142857,  6.78571429, 10.        ]])

In [69]:
a.cumsum()  # cumulative sum   
np.cumsum(a) # another way to call the command 

array([ 1.        ,  2.64285714,  4.92857143,  7.85714286, 11.42857143,
       15.64285714, 20.5       , 26.        , 32.14285714, 38.92857143,
       46.35714286, 54.42857143, 63.14285714, 72.5       , 82.5       ])

In [70]:
a = a.flatten() # transform the array to one-dimensional
a

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])